# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Openstack_Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OpenstackVM',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u865a\u62df\u673a\u540d\u5b57')),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField(verbose_name='\u5185\u5b58')),
                ('disk', models.IntegerField(verbose_name='\u78c1\u76d8\u5927\u5c0f')),
                ('operation', models.CharField(max_length=30, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('bit', models.IntegerField(verbose_name='\u4f4d\u6570')),
                ('volume', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
                ('vstatus', models.CharField(choices=[('1', '\u5f00\u542f'), ('0', '\u5173\u95ed')], max_length=4, verbose_name='\u72b6\u6001')),
            ],
            options={
                'ordering': ('-vstatus',),
            },
        ),
        migrations.CreateModel(
            name='Template_Iso',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=30)),
                ('bit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('L', '\u6d4b\u8bd5\u7ec4\u957f'), ('M', '\u6d4b\u8bd5\u6210\u5458')], max_length=8, verbose_name='\u7528\u6237\u89d2\u8272')),
                ('group', models.CharField(choices=[('1', '\u5e7f\u5dde\u4e00\u7ec4'), ('2', '\u5e7f\u5dde\u4e8c\u7ec4'), ('3', '\u6210\u90fd\u5206\u7ec4')], max_length=8, verbose_name='\u7528\u6237\u7ec4\u522b')),
                ('privilege', models.CharField(choices=[('True', '\u5df2\u6388\u6743'), ('False', '\u672a\u6388\u6743')], max_length=8, verbose_name='\u7528\u6237\u6743\u9650')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VM_Dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u76ee\u5f55\u7f16\u53f7')),
                ('dir_name', models.CharField(max_length=50, verbose_name='\u76ee\u5f55\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='VM_Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5b58\u50a8\u4e3b\u673a\u7f16\u53f7')),
                ('store_ip', models.CharField(max_length=15, verbose_name='IP\u5730\u5740')),
                ('store_name', models.CharField(max_length=50, verbose_name='\u5b58\u50a8\u4e3b\u673a\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='VMware_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Template_Iso')),
            ],
        ),
        migrations.CreateModel(
            name='VMware_VsphereVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('operation', models.CharField(max_length=30)),
                ('bit', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
                ('vstatus', models.CharField(choices=[('1', '\u5f00\u542f'), ('0', '\u5173\u95ed')], max_length=4)),
            ],
            options={
                'ordering': ('-vstatus',),
            },
        ),
        migrations.AddField(
            model_name='vmware_template',
            name='virtual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.VMware_VsphereVM'),
        ),
        migrations.AddField(
            model_name='openstack_iso',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Template_Iso'),
        ),
        migrations.AddField(
            model_name='openstack_iso',
            name='virtual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.OpenstackVM'),
        ),
    ]
